import { db } from "@server/db/index";
import { products } from "@server/db/schema/products";

export async function seedProducts() {
  await db.insert(products).values([
    {
      slug: "gaerballon",
      name: "Gärballon",
      description: "Großer Gärballon zur sicheren Vergärung von Met und Wein.",
      price: 24.9,
      stock: 15,
      imageUrl: "/products/balloon.webp",
      category: "Ausrüstung",
    },
    {
      slug: "flasche",
      name: "Flasche",
      description: "Hochwertige Glasflasche zur Abfüllung von Met und Bier.",
      price: 2.49,
      stock: 120,
      imageUrl: "/products/bottle.webp",
      category: "Ausrüstung",
    },
    {
      slug: "brau-paddel",
      name: "Brau Paddel",
      description: "Robustes Braupaddel zum Umrühren der Maische.",
      price: 12.9,
      stock: 20,
      imageUrl: "/products/brewingpaddle.webp",
      category: "Ausrüstung",
    },
    {
      slug: "zimtstangen",
      name: "Zimtstangen",
      description: "Aromatische Zimtstangen für Met, Likör und Gewürzbier.",
      price: 4.99,
      stock: 40,
      imageUrl: "/products/cinnamon.webp",
      category: "Gewürz",
    },
    {
      slug: "honig",
      name: "Honig",
      description: "Natürlicher Blütenhonig als Basis für hochwertigen Met.",
      price: 9.9,
      stock: 35,
      imageUrl: "/products/honey.webp",
      category: "Basiszutat",
    },
    {
      slug: "hefenaehrsalz",
      name: "Hefenährsalz",
      description: "Nährstoffmischung zur optimalen Versorgung der Hefe.",
      price: 3.49,
      stock: 60,
      imageUrl: "/products/nutritionalsalt.webp",
      category: "Zutat",
    },
    {
      slug: "kieselsol",
      name: "Kieselsol",
      description: "Kieselsol zur Klärung von Wein und Met.",
      price: 5.9,
      stock: 25,
      imageUrl: "/products/silicasol.webp",
      category: "Zutat",
    },
    {
      slug: "schwefelpulver-kaliumdisulfit",
      name: "Schwefelpulver Kaliumdisulfit",
      description: "Kaliumdisulfit zur Stabilisierung und Konservierung.",
      price: 6.9,
      stock: 30,
      imageUrl: "/products/sulfur.webp",
      category: "Zutat",
    },
    {
      slug: "sternanis",
      name: "Sternanis",
      description: "Intensives Gewürz für winterliche Met- und Bierrezepte.",
      price: 4.49,
      stock: 45,
      imageUrl: "/products/staranis.webp",
      category: "Gewürz",
    },
    {
      slug: "tannin",
      name: "Tannin",
      description: "Tannin zur geschmacklichen Verfeinerung von Met und Wein.",
      price: 5.49,
      stock: 18,
      imageUrl: "/products/tannin.webp",
      category: "Gewürz",
    },
    {
      slug: "hefe",
      name: "Hefe",
      description: "Leistungsstarke Trockenhefe für Met, Bier und Wein.",
      price: 2.99,
      stock: 80,
      imageUrl: "/products/yeast.webp",
      category: "Basiszutat",
    },
  ].map(({ category: _category, description, name, ...product }) => ({
    ...product,
    description: {
      de: description,
      en: description,
    },
    name: {
      de: name,
      en: name,
    },
  }))).onConflictDoNothing();
}
